//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public long AssignmentID { get; set; }
        public string SchoolToken { get; set; }
        public string Date { get; set; }
        public string SubjectToken { get; set; }
        public string GradeToken { get; set; }
    }
}
