//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long AttendanceID { get; set; }
        public string StudentToken { get; set; }
        public Nullable<int> Present { get; set; }
        public Nullable<int> Absent { get; set; }
        public int Year { get; set; }
    }
}
