//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<DesignationSetting> DesignationSettings { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<GradeSetting> GradeSettings { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<SchoolRegister> SchoolRegisters { get; set; }
        public virtual DbSet<SchoolSubjectSetting> SchoolSubjectSettings { get; set; }
        public virtual DbSet<StudentWall> StudentWalls { get; set; }
        public virtual DbSet<SubjectSetting> SubjectSettings { get; set; }
        public virtual DbSet<TypeSetting> TypeSettings { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Image> Images { get; set; }
    }
}
