//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public long GradeID { get; set; }
        public string GradeToken { get; set; }
        public string ClassAlpha { get; set; }
        public string ClassRoman { get; set; }
        public Nullable<int> ClassNumeric { get; set; }
        public string Section { get; set; }
    }
}
