//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public long ParentID { get; set; }
        public string ParentName { get; set; }
        public int EntryToken { get; set; }
        public string ContactNo { get; set; }
        public string SchoolToken { get; set; }
        public string ParentToken { get; set; }
        public string ParentTransactionToken { get; set; }
    }
}
