//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolRegister
    {
        public long SchoolID { get; set; }
        public string SchoolToken { get; set; }
        public string SchoolName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ImagePath { get; set; }
    }
}
