//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Slider
    {
        public long SliderID { get; set; }
        public string ImageToken { get; set; }
        public string SchoolToken { get; set; }
        [DisplayName("Image")]
        public string ImagePath { get; set; }

        //to work with file
        //this property is not inside our table so NotMapped property is added
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        //for the default image path
        public Slider()
        {
            ImagePath = "~/AppFiles/Images/Default/default_slider.jpg";
        }
    }
}
