//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPSchoolAppClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentWall
    {
        public long StudentWallID { get; set; }
        public string SchoolToken { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string StudentToken { get; set; }
        public string Title { get; set; }
    }
}
